### ISSUE TITLE
Bad size for the debug overlay

### ISSUE THREAD

**Issue by Totobal5** [shdwcat/Inspectron#1]
Hi i am looking to use this library!
but i have a problem with the default size of the debug overlay when used on an empty room with a player instance.

i think the error happen because i am using https://github.com/jack27121/STANNcam/releases/tag/v2.2.4 that modify some gui, window, camera and many other resulutions aspects of my game automatically.

here is a pic

![Runner_aPfIglyLHK](https://github.com/shdwcat/Inspectron/assets/90012149/63d27268-f32c-49e8-8326-c4c877b49c1c)

i need to say that the debug overlay cannot be moved too.

ps: i know this is on pre-release state but i find that if i test this library it will come out of this pre-release state faster.

**Comment by shdwcat** [comment]
Thanks for trying it out! If you go to the config file and set the default and minimum sizes smaller, she's that help? What's the resolution(s) of your game?

**Comment by Totobal5** [comment]
Hi!
Yeah i change the defaults values and it work perfect now!
Still i think this should be corrected because in the documentation appear that inspectron select the perfect size windows for the dbg_* view !!

still many thanks !

**Comment by shdwcat** [comment]
Yep, I will figure out a fix!

**Comment by shdwcat** [comment]
I believe this was fixed with the 1.0.0 release, please let me know if you're still having issues in the latest release
