### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by tthrelfo** [shdwcat/Inspectron#2]
Under the section entitled **Customize the Inspectron View for Different Objects**, there's a typo in the example code provided, as per the below:

```game-maker-language
Inspectron
.Section("player")
.Watch(nameof(player_health), "Health")
.Checkbox(nameof(invulnerable))
.BuiltIn()
``` 

Should be:

```game-maker-language
Inspectron()
.Section("player")
.Watch(nameof(player_health), "Health")
.Checkbox(nameof(invulnerable))
.BuiltIn();
``` 

(note the difference to the first line and also a bonus semicolon at the very end :D)

**Comment by shdwcat** [comment]
Fixed by 6254633ae6f21a06911bcc9daf2a9b475ab3353f
